"""empty message

Revision ID: 2f37790f0935
Revises: 5b738f39acc5
Create Date: 2021-11-22 14:38:28.805931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f37790f0935'
down_revision = '5b738f39acc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
