"""empty message

Revision ID: 4887c73e1324
Revises: 2bc99a769690
Create Date: 2021-11-22 09:19:37.329700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4887c73e1324'
down_revision = '2bc99a769690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_member', sa.Column('addtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_member', 'addtime')
    # ### end Alembic commands ###
