"""empty message

Revision ID: 5b738f39acc5
Revises: 446634712291
Create Date: 2021-11-22 14:37:04.290902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b738f39acc5'
down_revision = '446634712291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('pwd', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'pwd')
    # ### end Alembic commands ###
